version: "3.5"

services:
  db:
    image: postgres #:alpine3.19
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "140MB"
  
  adminer:
    image: adminer
    ports:
      - 8080:8080

  api01: &api
    image: arnaldogaldino/rinha-2024q1-crebito:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - PORT=3001
    ports:
      - "3001:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - PORT=3002
    ports:
      - "3002:8080"

  nginx:
    image: nginx #:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"
          
networks:
  default:
    name: rinha-nginx-2024q1
