version: "3.5"

services:
  db:
    image: postgres:alpine3.19
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "140MB"
    networks:
      - default

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"
    networks:
      - default

  api01: &api
    image: arnaldogaldino/rinha-2024q1-crebito:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - PORT=3001
      - ASPNETCORE_URLS=http://*:8081
    ports:
      - "3001:8081"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"
    networks:
      - default

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - PORT=3002
      - ASPNETCORE_URLS=http://*:8082
    ports:
      - "3002:8082"
    networks:
      - default
      
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
